"""
ANTIGRAVITY — Edge Engine: Threat / Event Engine
Extensible event system for generating structured alerts.
"""
import json
import logging
import uuid
from datetime import datetime, timezone
from dataclasses import dataclass, asdict
from typing import List, Optional

logger = logging.getLogger("antigravity.events")


@dataclass
class ThreatEvent:
    """Structured event generated by the edge engine."""
    event_id: str
    camera_id: str
    track_id: Optional[int]
    event_type: str
    object_class: str
    confidence: float
    coordinates: dict  # {"x": cx, "y": cy}
    timestamp: str
    metadata: Optional[dict] = None
    evidence_path: Optional[str] = None
    evidence_hash: Optional[str] = None

    def to_json(self) -> str:
        return json.dumps(asdict(self), default=str)

    def to_dict(self) -> dict:
        return asdict(self)


# Supported event types
EVENT_TYPES = [
    "PERSON_DETECTED",
    "VEHICLE_DETECTED",
    "TRIPWIRE_BREACH",
    "ZONE_ENTRY",
    "ZONE_EXIT",
    "MULTIPLE_TARGETS",
    "SUSPICIOUS_MOVEMENT",
    "CAMERA_OFFLINE",
]


class EventEngine:
    """
    Generates structured ThreatEvent objects from spatial events and detections.
    """

    def __init__(self, camera_id: str):
        self.camera_id = camera_id
        self._event_count = 0

    def create_event(
        self,
        event_type: str,
        track_id: Optional[int] = None,
        object_class: str = "unknown",
        confidence: float = 0.0,
        centroid: tuple = (0, 0),
        metadata: Optional[dict] = None,
        evidence_path: Optional[str] = None,
        evidence_hash: Optional[str] = None,
    ) -> ThreatEvent:
        """Create a structured threat event."""
        self._event_count += 1
        event = ThreatEvent(
            event_id=f"evt_{uuid.uuid4().hex[:12]}",
            camera_id=self.camera_id,
            track_id=track_id,
            event_type=event_type,
            object_class=object_class,
            confidence=confidence,
            coordinates={"x": centroid[0], "y": centroid[1]},
            timestamp=datetime.now(timezone.utc).isoformat(),
            metadata=metadata,
            evidence_path=evidence_path,
            evidence_hash=evidence_hash,
        )
        logger.info(
            f"Event created: {event_type} | Track #{track_id} | "
            f"{object_class} ({confidence:.2f})"
        )
        return event

    def from_spatial_event(self, spatial_event, **kwargs) -> ThreatEvent:
        """Create a ThreatEvent from a SpatialEvent."""
        return self.create_event(
            event_type=spatial_event.event_type,
            track_id=spatial_event.track_id,
            object_class=spatial_event.object_class,
            confidence=spatial_event.confidence,
            centroid=spatial_event.centroid,
            metadata={
                "zone_id": spatial_event.zone_id,
                "zone_name": spatial_event.zone_name,
            },
            **kwargs,
        )

    @property
    def total_events(self) -> int:
        return self._event_count
