@echo off
cd /d "d:\cloner"
git add .
git commit -m "mark48: Independent virtual fence editing for live camera vs media upload feeds | mark48.1: Fix AI detection in media feed | mark49: MinIO S3 evidence vault structure | mark49.1: Real target tracking and Web Audio breach alarm | mark50: 3-5s evidence video playback and 7-day persistent IndexedDB storage | mark50.1: Optical zoom plate magnifier and clean vault UI | mark50.2: Isolate camera stream breaches | mark50.3: Fix Alerts UI auto-shift and isolate camera fence alarms | mark51: Complete removal of static mock data and transition to client-side local persistence, real-time dynamic audit logs and reports | mark51.1: Multi-entity local IndexedDB and WebStorage persistence for evidence, alerts, fences, and audit logs | mark52: Blinking red geo-fence on perimeter breach and persistent automatic vehicle license plate capture with IndexedDB storage | mark53: Persistent global webcam and uploaded media streams across page navigation with zero-delay continuous live AI analysis | mark54: Rename AI Assistant to KAVACH BOT and fix Enter key execution with dedicated submit button | mark55: Minor UI/UX tactical enhancements with quick suggestion chips, illuminated navigation notches, and unified ANPR badges | mark56: Enable vehicle detection and perimeter breach tracking in geo fences with automatic ANPR license plate alert creation | mark57: Subtle UI and UX enhancements with ambient tactical glass highlights and glowing micro-interactions | mark58: Restore prominent media file upload buttons across Live Surveillance and Virtual Fence Studio | mark59: Add dedicated direct media upload buttons next to VLC in CameraPanel and ThermalFeedPlaceholder | mark60: Add selectable thermal camouflage defeat filter across all live surveillance and media feeds | mark60.1: Isolate virtual fence and tripwire breach glow per individual camera feed"
git push origin feature/rbac-security
git push origin feature/rbac-security:main
git push finall-round2 feature/rbac-security:main --force
git push finall-round2 feature/rbac-security --force
echo PUSH_COMPLETE
