/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0f131b',
        surface: '#0f131b',
        'surface-dim': '#0f131b',
        'surface-bright': '#353942',
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a32',
        'surface-container-highest': '#31353d',
        'on-surface': '#dfe2ed',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#dfe2ed',
        'inverse-on-surface': '#2c3039',
        outline: '#8c909f',
        'outline-variant': '#424754',
        'surface-tint': '#adc6ff',
        'surface-variant': '#31353d',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        secondary: '#95d4b0',
        'on-secondary': '#003823',
        'secondary-container': '#0d5135',
        'on-secondary-container': '#84c29f',
        'secondary-fixed': '#b0f1cb',
        'secondary-fixed-dim': '#95d4b0',
        'on-secondary-fixed': '#002112',
        'on-secondary-fixed-variant': '#0d5135',
        tertiary: '#ffb77d',
        'on-tertiary': '#4d2600',
        'tertiary-container': '#d97707',
        'on-tertiary-container': '#432100',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        label: ['"JetBrains Mono"', 'monospace'],
      },
      spacing: {
        '2xs': '0.125rem',
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '0.75rem',
        'base': '1rem',
        'lg': '1.25rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
        'gutter-sm': '0.75rem',
        'gutter-md': '1rem',
        'gutter-lg': '1.5rem',
        'panel-compact': '0.75rem',
        'panel-standard': '1.25rem',
      },
      boxShadow: {
        'tactical-plate': '-3px -3px 7px rgba(255, 255, 255, 0.03), 4px 4px 10px rgba(0, 0, 0, 0.55)',
        'tactical-extruded': '-4px -4px 8px rgba(255, 255, 255, 0.05), 5px 5px 12px rgba(0, 0, 0, 0.65)',
        'tactical-inset': 'inset 2px 2px 4px rgba(0, 0, 0, 0.6), inset -1px -1px 3px rgba(255, 255, 255, 0.04)',
        'tactical-depress': 'inset 3px 3px 6px rgba(0, 0, 0, 0.7), inset -1px -1px 2px rgba(255, 255, 255, 0.04)',
      },
    },
  },
  plugins: [],
};
